name: gan
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.14
  - numpy=1.26.4
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - matplotlib=3.8.3
  - pandas=2.2.1
  - typer=0.11.1
  - ipykernel=6.29.3
  - ipython=8.22.2
  - openpyxl=3.1.2
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
