Name: swat-test-config
Description: This file contains the configuration for the SWAT dataset.
d_model_path: ./models/madgan/discriminator_3.pt
g_model_path: ./models/madgan/generator_3.pt
attack_data: ./data/swat_test.csv
batch_size: 32
anomaly_threshold: 0.2
max_iter_for_reconstruction: 30 
print_every: 1

window_size: 90
window_stride: 10
n_features: 5
latent_space_dim: 30
test_batches: False
test_data_range: ([0, 30000])
resconstruction_weight: 0.001